use_frameworks!

target 'JDBAFgzipRequestSerializer_Example' do
  pod 'JDBAFgzipRequestSerializer', :path => '../'

  target 'JDBAFgzipRequestSerializer_Tests' do
    inherit! :search_paths

    
  end
end
